force-app/main/default/objects/Monster_Club__c/Monster_Club__c.object-meta.xml
<CustomObject>
    <label>Monster Club</label>
    <nameField>
        <label>Monster Club Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monsters Club</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monster_Club__c/fields/Club_Activity__c.field-meta.xml
<CustomField>
    <fullName>Club_Activity__c</fullName>
    <description>Club activity types</description>
    <inlineHelpText>Club activity types</inlineHelpText>
    <label>Club Activity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stomp around the house</fullName>
            </value>
            <value>
                <fullName>Jumping on the Bed</fullName>
            </value>
            <value>
                <fullName>Shuffle Songs</fullName>
            </value>
            <value>
                <fullName>Slimy Eyes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monster_Club__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact associated to a club</description>
    <inlineHelpText>Contact associated to a club</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Monsters Club</relationshipLabel>
    <relationshipName>Monsters_Club</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monster_Club__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestMonsterClubTrigger.cls
@isTest
public with sharing class TestMonsterClubTrigger {

    @TestSetup
    static void makeMonsterClubData(){

        Contact con = new Contact();
        con.LastName = 'Frank';
        con.FirstName = 'Ben';
        insert con;

        List<Monster_club__c> records = new List<Monster_club__c>();
        Monster_club__c mc = new Monster_club__c();
        mc.Name = 'Test Party';
        mc.Status__c = 'Not Started';
        mc.Club_Activity__c = 'Stomp around the house';
        mc.Contact__c = con.Id;
        records.add(mc);
        insert records;
    }
    @isTest
    static void test_create_monsterClubRecord() {
        Test.startTest();
            List<Monster_club__c> records = [SELECT Id, Name from Monster_club__c LIMIT 1];
        	records[0].Name = 'Test Party 1';
        	update records;
        Test.stopTest();
        System.assertEquals('Test Party 1' + ' - ' + String.valueOf(System.today()) , records[0].Name, 'Names do not match');
    }
}